#!/usr/bin/env bash
#this script install nginx and return a page that contains Holberton School
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start