#!/usr/bin/env bash
# Script install Nginx server and redirects /redirect_me
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
new_string="\\\trewrite ^/redirect_me https://www.youtube.com/ permanent;"
sudo sed -i "42i $new_string" /etc/nginx/sites-available/default
n_str="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "44i $n_str" /etc/nginx/sites-available/default
sudo service nginx restart