#!/usr/bin/env bash
# this script configures a new server and install HAproxy LB

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.6
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
sudo sed -i "20 i\ \nfrontend my_front\n\tbind *:80\n\tdefault_backend my_back" /etc/haproxy/haproxy.cfg
sudo sed -i "25 i\\backend my_back\n\tbalance roundrobin\n\tmode http\n\tserver 963-web-01 35.237.185.211:80 check\n\tserver 963-web-02 54.160.144.29:80 check\n" /etc/haproxy/haproxy.cfg
sudo service haproxy start