#!/usr/bin/env bash
# this script configures a new server and install HAproxy LB

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.5
sudo apt-gey -y update
sudo apt-get -y install haproxy=1.6.\*
sudo sed -i "20 i\ \nfrontend my_front\n\tbind *:80\n\tdefault_backend my_back" /etc/haproxy/haproxy.cfg
sudo sed -i "25 i\\backend my_back\n\tbalance roundrobin\n\tmode http\n\tserver 963-web-01 35.243.129.221\n\tserver 963-web-02 35.231.144.56\n" /etc/haproxy/haproxy.cfg
sudo service haproxy start