#!/usr/bin/env bash
# this script generates a MYSQL dump and creates a compresses file out of it
mysqldump --all-databases -u root -p"$1" > backup.sql
tar -czvf "$(date '+%d-%m-%Y').tar.gz" backup.sql