#!/usr/bin/env bash
# if 4 "bad luck" elif 8 "good luck" else "Holberton School" print
i=0
while [ $i -lt 10 ];
do
	if [ $i -eq 3 ];
	then
		echo "bad luck"
	elif [ $i -eq 7 ];
	then
	       	echo "good luck"
	else
	        echo "Holberton School"
	fi
	let i+=1
done
