#!/usr/bin/env bash
# print 1.. 20 and case 4 "bad luck china" 9 "bad luck japan" 17 "bad luck italy"
i=1
while [ $i -le 20 ];
do
	echo "$i"
	case $i in
	        4)
			echo "bad luckm from China"
	     	     	;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	let i+=1
done
	
