#!/usr/bin/env bash
#this script fix a container so that is running as the nginx user
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
pkill -9 apache
su nginx -c "service nginx restart"
