#!/usr/bin/env bash
#this script configures a new server with nginx conf file
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/nginx.conf
su nginx -c "service nginx restart"